# Generated by Django 3.2.16 on 2022-11-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_workout_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['workout']},
        ),
    ]
