# Generated by Django 3.2.16 on 2022-11-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_workout_app', '0002_alter_exercise_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['created_on']},
        ),
    ]
