# Generated by Django 3.2.16 on 2022-11-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_workout_app', '0003_alter_exercise_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
