# Generated by Django 3.2.16 on 2022-11-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_workout_app', '0004_alter_workout_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
