# Generated by Django 3.2.16 on 2022-11-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_workout_app', '0005_auto_20221114_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['updated_on']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='updated_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
