# Generated by Django 3.2.16 on 2022-11-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_workout_app', '0006_auto_20221114_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
