# Generated by Django 3.2.16 on 2022-11-14 16:43

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_workout_app', '0007_alter_exercise_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(limit_choices_to=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='create_workout_app.workout'),
        ),
    ]
