# Generated by Django 3.2.16 on 2022-11-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_workout_app', '0008_auto_20221114_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='create_workout_app.workout'),
        ),
    ]
